#! /usr/bin/env python

"""
Illustrate the effect of weak order constraints for the build (generates diagrams)

waf configure clean build -j2 --dwidth=800 --dtitle='GAP on "waf -j2"' --dmaxtime=15
waf configure clean build -j2 --dwidth=800 --dtitle='Default constraints on "waf -j2"' --dmaxtime=15
waf configure clean build -j2 --dwidth=800 --dtitle='Additional constraints on "waf -j2"' --dmaxtime=15
"""

from waflib import Task

def options(ctx):
	ctx.load('parallel_debug')
	ctx.add_option('--diag', default='1', help='diagram 1,2 or 3')

def configure(ctx):
	ctx.load('parallel_debug')

def build(bld):
	bld.jobs = 2
	bld.options.dnotooltip = True
	diag = bld.options.diag
	if diag == '1':
		bld.options.dtitle = 'Same priority for green and red tasks (waf -j2)'
	elif diag == '2':
		bld.options.dtitle = 'Increased red task weight (waf -j2)'
	elif diag == '3':
		bld.options.dtitle = 'Gap of green tasks between red and blue (waf -j2)'
		from waflib import Runner
		Runner.GAP = 5

	if diag in '12':
		bld.options.dmaxtime=7.1
		for x in range(5):
			bld(rule='sleep 1', color='GREEN', name='green', always=True)
		tg = bld(rule='sleep 5', color='RED', name='red', always=True)
	else:
		bld(rule='sleep 1', color='BLUE', name='blue', always=True)
		for x in range(80):
			bld(rule='sleep 0.1', color='GREEN', name='green', always=True)
		tg = bld(rule='sleep 6', color='RED', name='red', always=True, after='blue')

	if diag in '23':
		tg.post()
		tg.tasks[0].weight = 20

	def copy_to(ctx):
		if diag == '1':
			name = 'tasks_nosort.eps'
		elif diag == '2':
			name = 'tasks_sort.eps'
		elif diag == '3':
			name = 'weak.eps'
		ctx.exec_command('inkscape pdebug.svg --export-eps=../../%s' % name, cwd=bld.srcnode.abspath())

	bld.add_post_fun(copy_to)

